
import numpy as np
import re
from langchain_openai import OpenAIEmbeddings,ChatOpenAI
from vectordb.vector_db_manager import VectorDBManager
from pinecone import Pinecone, IndexModel, ServerlessSpec

from markdown_it import MarkdownIt  
from markdown_it.tree import SyntaxTreeNode

from io import BytesIO
import pymupdf.layout
import pymupdf4llm
import pymupdf


from pdf_pipeline.etree import EmbedTreeNode 
from pdf_pipeline.gdoctree import GdocTreeNode
from googledoc.googledoc import GoogleDocsEditor
from lexical.lexical_algs import extract_text_similarity_jaccard
from dotenv import load_dotenv
import os
import time
load_dotenv(os.path.join(os.environ.get('LAMBDA_TASK_ROOT', ''), '.env'))



class superdoc():
    #Clean up init
    def __init__(self,DOCUMENT_ID:str|None,COURSE_ID:str,index_name=os.getenv("PINECONE_INDEX", "superdoc-headings")):
        self.DOCUMENT_ID = DOCUMENT_ID
        self.COURSE_ID = COURSE_ID
        self.docs_editor = GoogleDocsEditor()
        if DOCUMENT_ID is None: 
            self.DOCUMENT_ID = self.docs_editor.create_google_doc(name=COURSE_ID).get('documentId')

        self.db = VectorDBManager(pc=Pinecone(os.environ.get("PINECONE_API_KEY")))
        self.db.initVectorStore(index_name=index_name, embedding=OpenAIEmbeddings(api_key=os.getenv("OPENAI_API_KEY")))
        
        self.docs_editor.get_document_structure(document_id=self.DOCUMENT_ID)
        self.emb_model =OpenAIEmbeddings(api_key=os.getenv("OPENAI_API_KEY")) 
    
    def pdf_to_syntree(self,stream:BytesIO) -> SyntaxTreeNode:
        doc = pymupdf.open(stream=stream)
        markdown = pymupdf4llm.to_markdown(doc)
        mdit = MarkdownIt()
        md = mdit.parse(markdown)
        return SyntaxTreeNode(md)
    
    def stree_to_etree(self,stree:SyntaxTreeNode) -> EmbedTreeNode:
        print("Building Semantic Tree...")
        root = EmbedTreeNode._init_tree(root_node=stree, emb_model=self.emb_model)
        EmbedTreeNode._embed_tree_(root)
        EmbedTreeNode._calc_block_len(root)
        return root

        
    '''
    
        Main merging algorithm

    '''

    def merge_pdf_hierarchical(self, stream: BytesIO):
        """
        New tree-based merge functionality that respects document hierarchy 
        and handles custom heading injection.
        """
        print(f"---Synchronizing Document---")
        self.sync_headings()
        print(f"--- Starting Hierarchical Merge for Doc: {self.DOCUMENT_ID} ---")
        
        # 1. Convert PDF to Syntax Tree (Markdown-it structure)
        # Note: Ensure pdf_to_syntree is available in your scope
        start_time = time.perf_counter()
        synt_tree = self.pdf_to_syntree(stream=stream) 
        
        # 2. Build the Semantic EmbedTree and calculate embeddings
        # This populates node.emb and node.mean_emb (as native Python lists)
        root = self.stree_to_etree(stree=synt_tree)
        
        # 3. Fetch existing headings from Pinecone for this course/doc
        # This allows the tree to find where this new PDF "fits" into existing topics
        existing_headings = self.db.get_all_headings_for_doc(
            course_id=self.COURSE_ID, 
            superdoc_id=self.DOCUMENT_ID
        )
        
        # 4. Inject Custom Headings and detect "Stragglers"
        # new_cust_nodes: Brand new headings generated by LLM for orphaned content
        # all_cust_nodes: Total set of custom nodes (existing + new) to be rendered
        new_cust_nodes, all_cust_nodes = root.reconcile_structure(headings=existing_headings)
        
        #Lexical Redundnacy check
        if all_cust_nodes:
            print("Running Lexical Redundancy Check on Tree Branches...")
            self.docs_editor.get_document_structure(document_id=self.DOCUMENT_ID)  # <-- fresh doc obj
            
            for branch in all_cust_nodes:
                if hasattr(branch, 'children') and branch.children:
                    heading_text = getattr(branch, 'content', '').strip()
                    print(f"Checking {len(branch.children)} nodes under: '{heading_text}'")
                    branch.children = self.lexical_redundancyCheck(
                        nodes=branch.children,
                        heading=heading_text  # <-- pass heading explicitly
                    )
            
            # Remove branches that are now empty after pruning
            all_cust_nodes = [b for b in all_cust_nodes if len(getattr(b, 'children', [])) > 0]


        # 5. Sync new structural nodes to Vector DB
        # We only append the NEWLY generated headings so we don't duplicate existing ones
        if new_cust_nodes:
            print(f"Syncing {len(new_cust_nodes)} new custom headings to Pinecone...")
            self.db.append_documents(
                e_branches=new_cust_nodes, 
                course_id=self.COURSE_ID, 
                superdoc_id=self.DOCUMENT_ID
            )

        # 6. Render to Google Docs
        # This uses the specialized hierarchical renderer
        print(f"Rendering {len(all_cust_nodes)} custom branches to Google Doc...")
        render_start = time.perf_counter()
        self.docs_editor.get_document_structure(document_id=self.DOCUMENT_ID)
        self.docs_editor.mutate_named_ranges(document_id=self.DOCUMENT_ID)
        # This method handles named ranges and structural formatting
        self.docs_editor.render_etree_custom_nodes(
            superdoc_id=self.DOCUMENT_ID, 
            all_cust_nodes=all_cust_nodes
        )
        
        end_time = time.perf_counter()
        print(f"Total Merge Process completed in: {(end_time - start_time):.2f}s")
        print(f"Google Doc Render took: {(end_time - render_start):.2f}s")

    '''
    
        Heading management
    
    '''

    def delete_heading(self,old_heading:str): 
        self.docs_editor.delete_heading(old_heading=old_heading)
        self.db.remove_vectordb_heading(heading=old_heading,course_id=self.COURSE_ID,superdoc_id=self.DOCUMENT_ID)
    
    def create_heading(self,new_heading:str):
        self.docs_editor.create_heading(new_heading=new_heading)
        self.db.create_vectordb_heading(heading_text=new_heading,course_id=self.COURSE_ID,superdoc_id=self.DOCUMENT_ID)

    def update_heading(self,old_heading:str,new_heading:str):
        '''Updates old_heading in both google docs and vectorDb'''

        #update googledoc heading named range
        self.docs_editor.update_heading(old_heading=old_heading,new_heading=new_heading)
        self.db.replace_vectordb_heading_with_text(old_heading=old_heading,new_heading_text=new_heading,course_id=self.COURSE_ID,superdoc_id=self.DOCUMENT_ID)

    def sync_headings(self): 
        self.fix_new_content() 
        self.fix_heading_update()


    def fix_heading_update(self): 
        """
        Synchronizes the document structure from Google Docs with Pinecone.
        Finds changed or deleted headings and processes them using VectorDBManager
        batch methods for high-efficiency synchronization.
        """
        #Fetch current live doc structure and existing DB headings via the manager
        self.docs_editor.get_document_structure(document_id=self.DOCUMENT_ID) 
        doc_headings = self.db.get_all_headings_for_doc(
            course_id=self.COURSE_ID, 
            superdoc_id=self.DOCUMENT_ID
        )

        delete_ids = []
        headings_to_embed = []
        print(f"Num of vector-db-headings:{doc_headings}")
        #Extract and analyze document content
        for db_entry in doc_headings: 
            heading_text = db_entry.get("heading")
            vector_id = db_entry.get("id")
            
            # Extract text using the decoupled index-based method
            content_under_heading = self.docs_editor.get_text_in_range_from_doc_obj(heading_text)
            print(f"Content of {heading_text}: {content_under_heading}")
            # Case 1: Heading or its content no longer exists in the document
            if not content_under_heading: 
                delete_ids.append(vector_id)
                continue
                  
            # Case 2: Content exists, but the literal "Heading:" prefix has changed
            prefix_target = f"{heading_text}:"
            if prefix_target not in content_under_heading: 
                delete_ids.append(vector_id)
                
                # Identify the new heading string (text before the first colon)
                parts = content_under_heading.split(":", 1)
                potential_new_heading = parts[0].strip()
                
                if potential_new_heading:
                    headings_to_embed.append(potential_new_heading)

        #Batch Query OpenAI for all modified headings
        vectors_to_upsert = []
        if headings_to_embed:
            print(f"Batch embedding {len(headings_to_embed)} changed headings...")
            
            # Chunking OpenAI requests specifically to stay under token/payload limits
            for text_chunk in self._chunk_list(headings_to_embed, 500):
                embedded_vectors = self.emb_model.embed_documents(text_chunk)
                
                for text, vector in zip(text_chunk, embedded_vectors):
                    vectors_to_upsert.append({
                        "id": self.db.generate_timestamp_id(self.COURSE_ID),
                        "values": vector,
                        "metadata": {
                            "superdoc": self.DOCUMENT_ID,
                            "heading": text,
                        }
                    })

        #Execute Batch Operations via VectorDBManager
        # The manager handles the 1,000-vector Pinecone limit internally.
        
        if delete_ids:
            self.db.batch_delete_vectors(
                vector_ids=delete_ids, 
                course_id=self.COURSE_ID
            )

        if vectors_to_upsert:
            self.db.batch_upsert_vectors(
                vectors=vectors_to_upsert, 
                course_id=self.COURSE_ID
            )
            
        print("Superdoc synchronization complete.")
                 

    def fix_new_content(self): 
        """
        Scans un-indexed document gaps for user-defined <HEADING>: tags.
        Extracts the heading, formats it in the Doc, and syncs to Pinecone.
        
        **NOTE**: Using pineconedb embeddings not openai
        """
        # Fetch live structure and identify gaps (skips)
        self.docs_editor.get_document_structure(document_id=self.DOCUMENT_ID) 
        skips = self.docs_editor.catch_skips()
        
        # This will hold the final payloads for Pinecone
        vectors_to_upsert = []
        
        # Queue for batch updating Google Docs
        headings_queue = []

        # Iterate through skips to find the <HEADING>: pattern
        for skip in skips:
            start_idx = skip.get('startIndex')
            end_idx = skip.get('endIndex')
            
            # Extract raw text from this specific skip
            text = self.docs_editor.get_text_in_indices_from_doc_obj(start_idx, end_idx)
            
            if not text:
                continue

            # Regex finds anything inside < > followed by a colon
            # Example: matches "<Biology Notes>:" and captures "Biology Notes"
            matches = list(re.finditer(r"<(.*?)>:", text))

            if not matches:
                continue

            # Process matches to build the queues
            for match in matches:
                extracted_heading = match.group(1).strip()
                
                # Get the substring in the text leading up to this specific match
                text_before_match = text[:match.start()]
                
                # Use utf-16 len calcs for index mapping
                utf16_offset = self.docs_editor.text_utf16_len(text_before_match)
                tag_start_in_doc = start_idx + utf16_offset

                print(f"Detected manual heading tag: '{extracted_heading}'")

                # Queue for Google Docs Batch Operation
                headings_queue.append({
                    'heading': extracted_heading,
                    'startIndex': tag_start_in_doc
                })

                # Queue for Pinecone Vector DB
                # Sample the content directly following the tag
                content_after_tag = text[match.end():].strip()[:500] 
                
                vectors_to_upsert.append({
                    "heading": extracted_heading,
                    "content_sample": content_after_tag
                })

        # Batch update Google Docs with all gathered headings
        if headings_queue:
            self.docs_editor.batch_create_headings_and_named_ranges(headings_queue)

        # Batch process embeddings and delegate upsert to VectorDBManager
        if vectors_to_upsert:
            print(f"Batch embedding {len(vectors_to_upsert)} manual headings...")
            
            # Extract just the heading strings for the embedding model
            heading_strings = [v["heading"] for v in vectors_to_upsert]
            embedded_vectors = self.emb_model.embed_documents(heading_strings)
            
            pinecone_payload = []
            for i, vector in enumerate(embedded_vectors):
                original_data = vectors_to_upsert[i]
                pinecone_payload.append({
                    "id": self.db.generate_timestamp_id(self.COURSE_ID),
                    "values": vector,
                    "metadata": {
                        "superdoc": self.DOCUMENT_ID,
                        "heading": original_data["heading"],
                        "content_preview": original_data["content_sample"][:200] 
                    }
                })
            
            # Direct push to vector db
            self.db.batch_upsert_vectors(
                vectors=pinecone_payload, 
                course_id=self.COURSE_ID
            )

        print("Superdoc manual tag sync complete.")


    def _chunk_list(self, lst, n):
        """Helper generator to split lists into batch-safe payloads."""
        for i in range(0, len(lst), n):
            yield lst[i:i + n]


    '''
    
        Google Doc creation and fetching
    
    '''


    def create_document(self,name:str,course_id): 
        return self.docs_editor.create_google_doc(name=name,courseid=course_id)



    def get_docids(self, course_id: str) -> dict: 
        # 1. Get the list of document IDs (assuming this returns a list)
        document_ids = self.docs_editor.get_docids(courseid=course_id)
        
        # 2. Initialize the dictionary
        docs_map = {}
        
        for docid in document_ids:
            # 3. Get the document structure/metadata
            # Usually, the title/name is found in the 'title' field of the doc object
            doc_structure = self.docs_editor.get_document_structure(docid)
            
            # Extract the name (adjust key based on your get_document_structure return type)
            doc_name = doc_structure.get('title', 'Untitled Document')
            
            # 4. Map the Name to the ID
            docs_map[doc_name] = docid
            
        return docs_map
    

    '''

        Lexical Redundancy

    '''
    
    def lexical_redundancyCheck(self, nodes: list, heading: str):
        print(f"\n[DEBUG] Starting Check for {len(nodes)} nodes under '{heading}'")
        
        pruned_tree = []
        LEXICAL_CHECK_CONSTANT = 0.7

        raw_doc_text = self.docs_editor.get_text_in_range_from_doc_obj(heading)
        existing_lines = [line.strip() for line in (raw_doc_text or "").split("\n") if line.strip()]
        print(f"  [CACHE] {len(existing_lines)} lines in GDoc under '{heading}'")

        for i, node in enumerate(nodes):
            node_text = self._extract_leaf_text(node)  # ← clean text from content attr

            if not node_text:
                print(f"  [NODE {i}] SKIP: No text found.")
                pruned_tree.append(node)
                continue

            is_redundant = False
            highest_score = 0

            for line in existing_lines:
                score = extract_text_similarity_jaccard(node_text, line)
                if score > highest_score:
                    highest_score = score
                if score >= LEXICAL_CHECK_CONSTANT:
                    is_redundant = True
                    break

            if not is_redundant:
                pruned_tree.append(node)
                print(f"  [KEEP]  '{node_text[:60]}' (max sim: {highest_score:.2f})")
            else:
                print(f"  [PRUNE] '{node_text[:60]}' (score: {highest_score:.2f})")

        print(f"[DEBUG] Done. Kept {len(pruned_tree)}/{len(nodes)}\n")
        return pruned_tree


    def _extract_leaf_text(self, node) -> str:
        """Walk down the tree until we find a node with actual content."""
        content = node.content.strip() if node.content else ""
        if content:
            return content
        for child in node.children:
            result = self._extract_leaf_text(child)
            if result:
                return result
        return ""
    
if __name__ == '__main__': 
    with open("files/basic-text.pdf", "rb") as f:
        pdf_bytes = f.read()
    strm = BytesIO(pdf_bytes)

    sd = superdoc(DOCUMENT_ID='1Q1whz1kFN9wj1_mamWgaDbKh7przNmc5owdOSNovC04',COURSE_ID="Goof1202")
    sd.merge_pdf_hierarchical(stream=strm)
    #sd.sync_headings()
    #sd.create_document(name="Hellow",course_id="RHET1302")
    #sd.merge_pdf()
   # sd.update_heading(old_heading="Introduction",new_heading="GoofyGoober")
    #sd.create_heading(new_heading="Trump giving Kirk to Bubba")
    #print(f"Heading content:{sd.docs_editor.get_text_in_range_from_doc_obj("Trump giving Kirk to Stein")}")
    #sd.fix_new_content()